import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { Writable } from 'node:stream'
import { write } from '../report/html.js'

const SHARED = new URL('../../../shared/report/', import.meta.url)

function render (results, meta) {
  const chunks = []
  const sink = new Writable({
    write (chunk, enc, cb) {
      chunks.push(Buffer.from(chunk))
      cb()
    }
  })
  return write(sink, results, meta).then(() => Buffer.concat(chunks).toString('utf8'))
}

function loadFixture () {
  const f = JSON.parse(readFileSync(new URL('fixture.json', SHARED), 'utf8'))
  const meta = { ...f.meta }
  if (meta.generatedAt) meta.generatedAt = new Date(meta.generatedAt)
  return { meta, results: f.results }
}

// The cross-implementation drift alarm: this renderer must reproduce the
// shared golden (generated by the canonical Go implementation via
// `make golden` in packages/go) byte-for-byte.
test('golden: byte-identical with the Go renderer', async () => {
  const { meta, results } = loadFixture()
  const got = await render(results, meta)
  const golden = readFileSync(new URL('golden.html', SHARED), 'utf8')
  assert.equal(got, golden,
    'rendered report differs from shared/report/golden.html — if the change is intentional, regenerate via `make golden` in packages/go and re-verify')
})

test('deterministic output', async () => {
  const { meta, results } = loadFixture()
  assert.equal(await render(results, meta), await render(results, meta))
})

test('omitSkipped drops skipped vectors but keeps blocked', async () => {
  const { meta, results } = loadFixture()
  const out = await render(results, { ...meta, omitSkipped: true })
  assert.ok(!out.includes('versioning-0004'))
  assert.ok(out.includes('versioning-0003'))
})

test('escaping matches the Go entity set', async () => {
  const { meta, results } = loadFixture()
  const out = await render(results, meta)
  assert.ok(!out.includes("<script>alert('x & y')</script>"), 'script content must be escaped')
  assert.ok(out.includes('&lt;script&gt;alert(&#39;x &amp; y&#39;)&lt;/script&gt;'))
  // Go's escaper leaves ` = / alone — mustache.js's default would break parity.
  assert.ok(out.includes('`tick` = eq'), 'backtick/equals/slash must not be escaped')
})

test('empty run renders a valid page', async () => {
  const out = await render([], {})
  assert.ok(out.startsWith('<!doctype html>'))
  assert.ok(out.includes('—'))
})

test('every card links to its vector definition', async () => {
  const { meta, results } = loadFixture()
  const out = await render(results, meta)
  assert.ok(out.includes('href="https://raw.githubusercontent.com/cloud-portable/s3vectors/main/vectors/multipart.json#:~:text=%22id%22%3A%20%22multipart-0007%22"'))
  assert.equal(out.split('View vector definition').length - 1, results.length)
  assert.equal(out.split('View original test').length - 1, 1)
})
