import io
import json
import unittest
from pathlib import Path

from cloud_portable_s3tests import VectorResult
from cloud_portable_s3tests.report import Meta, html

SHARED = Path(__file__).resolve().parents[3] / "shared" / "report"


def load_fixture():
    f = json.loads((SHARED / "fixture.json").read_text("utf-8"))
    return Meta.from_dict(f["meta"]), [VectorResult.from_dict(r) for r in f["results"]]


def render(results, meta) -> bytes:
    buf = io.BytesIO()
    html.write(buf, results, meta)
    return buf.getvalue()


class TestReportHtml(unittest.TestCase):
    # The cross-implementation drift alarm: this renderer must reproduce the
    # shared golden (generated by the canonical Go implementation via
    # `make golden` in packages/go) byte-for-byte.
    def test_golden_byte_identical_with_the_go_renderer(self):
        meta, results = load_fixture()
        got = render(results, meta)
        golden = (SHARED / "golden.html").read_bytes()
        self.assertEqual(
            got, golden,
            "rendered report differs from shared/report/golden.html — if the change is intentional, "
            "regenerate via `make golden` in packages/go and re-verify",
        )

    def test_deterministic_output(self):
        meta, results = load_fixture()
        self.assertEqual(render(results, meta), render(results, meta))

    def test_omit_skipped_drops_skipped_vectors_but_keeps_blocked(self):
        meta, results = load_fixture()
        meta.omit_skipped = True
        out = render(results, meta).decode()
        self.assertNotIn("versioning-0004", out)
        self.assertIn("versioning-0003", out)

    def test_escaping_matches_the_go_entity_set(self):
        meta, results = load_fixture()
        out = render(results, meta).decode()
        self.assertNotIn("<script>alert('x & y')</script>", out, "script content must be escaped")
        self.assertIn("&lt;script&gt;alert(&#39;x &amp; y&#39;)&lt;/script&gt;", out)
        # Go's escaper leaves ` = / alone.
        self.assertIn("`tick` = eq", out, "backtick/equals/slash must not be escaped")

    def test_empty_run_renders_a_valid_page(self):
        out = render([], Meta()).decode()
        self.assertTrue(out.startswith("<!doctype html>"))
        self.assertIn("—", out)

    def test_every_card_links_to_its_vector_definition(self):
        meta, results = load_fixture()
        out = render(results, meta).decode()
        self.assertIn(
            'href="https://raw.githubusercontent.com/cloud-portable/s3vectors/main/vectors/multipart.json'
            '#:~:text=%22id%22%3A%20%22multipart-0007%22"',
            out,
        )
        self.assertEqual(out.count("View vector definition"), len(results))
        self.assertEqual(out.count("View original test"), 1)


if __name__ == "__main__":
    unittest.main()
